#!/usr/bin/env php
<?php

/**
 * Ultimate Unit Test Generator (Uutg)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Marius Strajeru
 */

declare(strict_types=1);

if (php_sapi_name() !== "cli") {
    exit('Test generator can be executed from cli only');
}

print_r($GLOBALS);
if (isset($GLOBALS['_composer_autoload_path'])) {
    define('UUTG_COMPOSER_INSTALL', $GLOBALS['_composer_autoload_path']);
    unset($GLOBALS['_composer_autoload_path']);
} else {
    foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
        if (file_exists($file)) {
            define('UUTG_COMPOSER_INSTALL', $file);
            break;
        }
    }

    unset($file);
}

if (!defined('UUTG_COMPOSER_INSTALL')) {
    die("Cannot find autoload file\n");
}

require UUTG_COMPOSER_INSTALL;

$options = getopt("", ["class:", "config::"]);
$configFile = $options['config'] ?? __DIR__.'/./uutg.php.dist';

echo $configFile;echo "\n";
if (!file_exists($configFile)) {
    exit(sprintf("Config file '%s' does not exist\n", $configFile));
}
$config = new \Umc\Uutg\Config(include $configFile);

$app = new \Umc\Uutg\Uutg(
    $config,
    $options['class'] ?? null
);

exit($app->run());
